### ISSUE TITLE
Tab bars don't cope well with narrow windows

### ISSUE THREAD

**Issue by runrevmark** [livecode/livecode-ide#593]
Particularly when in label mode (but it happens in icon mode too), the headers on the IDE palettes can end up with the tabs under the action buttons on the right hand-side.

We could make them wrap to a new line (like Windows Tab Controls do).

We could make little arrows appear left and right to scroll them (I think Safari did this for a while - or Chrome).

We could make a popup appear at the end with any which 'fall' off.

I'm not sure which is the best - there might be other options to.

![screen shot 2015-10-23 at 14 02 34](https://cloud.githubusercontent.com/assets/3985298/10693254/f88bd6b0-798e-11e5-9ab4-76a2219e41b5.png)

**Comment by jameshale** [comment]
The simplest interim solution would be to not allow the window (esp in the PI) to resize less than the width required to show all the labels/icons. That way you always see the available tabs. (This was one of the main attractions of the new PI.)
Having a popup appear is like reverting to the old PI.
Having them wrap to a second line would be cool but then I am not the one coding it :-)
I notice Photoshop cannot make up its mind having multiple lines of icons fixed, wraping, and single line fixed with min width.

p.s. looking at the image above I find the text of the labels significantly more pleasing than the text in the pane itself.

**Comment by livecodeali** [comment]
Thanks @jameshale, I think we'll implement the interim solution for now.

I kind of agree with you about the popup/scroller options, but I'm really not a fan of wrapping tabs to a second line either...  I'm not sure what my preference is!
