### ISSUE TITLE
Property Inspector: Not all objects in the list provided exist

### ISSUE THREAD

**Issue by mwieder** [livecode/livecode-ide#709]
I tried to inspect the properties of the "Style" control of card 1002 of stack "revPropertyInspector1" using LC8.0-dp10 on 64-bit linux Mint 17 and was greeted with the following message in the message box:

ERROR: Not all objects in the list provided exist
line: 4426
handler: __revIDEPropertiesInfoOfSection
script object: stack "/opt/livecode/livecodecommunity-8.0.0-dp-10.x86_64/Toolset/libraries/revidelibrary.8.livecodescript"

**Comment by livecodeali** [comment]
This has always been something of an issue with the property inspector (although before it just switched to various different objects rather than throwing an error).

@mwieder What were you expecting to happen? I guess we should just implement whatever that is :-)

Perhaps the inspector in question should lock and open a new instance?
